### ISSUE TITLE
Penalty and score function in Pelt is set to NULL

### ISSUE THREAD

**Issue by YuliaRubanova** [harrig12/BCB430#1]
In `find_changepoints_pelt` penalty and score function are set to   `penalty = TrackSig.options()$pelt_penalty, score_fxn = TrackSig.options()$pelt_score_fxn`.
However, in options-TrackSig.R   pelt_penalty and  pelt_score_fxn are set to NULL.

The package crashes with the message "score_fxn not found".

**Comment by YuliaRubanova** [comment]
In the previous commit the penalty was set to as follows: `penalty = (n_sigs - 1) * log(n_bins), score_fxn = log_likelihood_mixture_multinomials`.

**Comment by harrig12** [comment]
Should be resolved with commit 00fb6924d77b22358d5223d3d0d4c5fc8b430cae
